local colors = require("cassiopeia.utils").colors
local styles = require("cassiopeia.utils").styles
local Group = require("cassiopeia.utils").Group

Group.new('Boolean', colors.purple, nil, styles.italic)
Group.new('Character', colors.yellow, nil)
Group.new('Comment', colors.grey, nil, styles.italic)
Group.new('Conditional', colors.red, nil, styles.italic)
Group.new('Constant', colors.orange, nil, styles.italic)
Group.new('Define', colors.red, nil)
Group.new('Delimiter', colors.fg, nil)
Group.new('Error', colors.red, nil)
Group.new('Exception', colors.red, nil)
Group.new('Float', colors.purple, nil)
Group.new('Function', colors.orange, nil)
Group.new('Identifier', colors.orange, nil, styles.italic)
Group.new('Ignore', colors.grey, nil)
Group.new('Include', colors.red, nil)
Group.new('Keyword', colors.red, nil, styles.italic)
Group.new('Label', colors.purple, nil)
Group.new('Macro', colors.purple, nil)
Group.new('Number', colors.purple, nil)
Group.new('Operator', colors.red, nil)
Group.new('PreCondit', colors.red, nil)
Group.new('PreProc', colors.red, nil)
Group.new('Repeat', colors.red, nil, styles.italic)
Group.new('Special', colors.purple, nil)
Group.new('SpecialChar', colors.purple, nil)
Group.new('SpecialComment', colors.grey, nil, styles.italic)
Group.new('Statement', colors.red, nil, styles.italic)
Group.new('StorageClass', colors.blue, nil, styles.italic)
Group.new('String', colors.yellow, nil)
Group.new('Structure', colors.blue, nil, styles.italic)
Group.new('Tag', colors.orange, nil)
Group.new('Title', colors.red, nil, styles.bold)
Group.new('Todo', colors.blue, nil, styles.underline)
Group.new('Type', colors.blue, nil, styles.italic)
Group.new('Typedef', colors.red, nil)
Group.new('Underlined', colors.none, nil, styles.underline)
