local colors = require('cassiopeia.utils').colors
local styles = require('cassiopeia.utils').styles
local Group = require('cassiopeia.utils').Group


Group.new('ColorColumn'      , colors.none       , colors.bg1      , nil                              )
Group.new('Conceal'          , colors.grey       , colors.none     , nil                              )
Group.new('Cursor'           , colors.none       , colors.none     , styles.reverse                   )
Group.new('CursorColumn'     , colors.none       , colors.bg1      , nil                              )
Group.new('CursorLine'       , colors.none       , colors.bg1      , nil                              )
Group.new('CursorLineNr'     , colors.fg         , colors.bg1      , nil                              )
Group.new('Debug'            , colors.yellow     , colors.none     , nil                              )
Group.new('DiffAdd'          , colors.diff_green , colors.none     , nil                              )
Group.new('DiffChange'       , colors.diff_blue  , colors.none     , nil                              )
Group.new('DiffDelete'       , colors.diff_red   , colors.none     , nil                              )
Group.new('DiffText'         , colors.none       , colors.none     , styles.reverse                   )
Group.new('Directory'        , colors.green      , colors.none     , nil                              )
Group.new('EndOfBuffer'      , colors.bg0        , colors.bg0      , nil                              )
Group.new('ErrorMsg'         , colors.red        , colors.none     , styles.bold + styles.underline   )
Group.new('FoldColumn'       , colors.grey       , colors.bg1      , nil                              )
Group.new('Folded'           , colors.grey       , colors.bg1      , nil                              )
Group.new('IncSearch'        , colors.bg0        , colors.bg_red   , nil                              )
Group.new('LineNr'           , colors.grey       , colors.none     , nil                              )
Group.new('MatchParen'       , colors.none       , colors.bg4      , nil                              )
Group.new('ModeMsg'          , colors.fg         , colors.none     , styles.bold                      )
Group.new('MoreMsg'          , colors.blue       , colors.none     , styles.bold                      )
Group.new('NonText'          , colors.bg4        , colors.none     , nil                              )
Group.new('Normal'           , colors.fg         , colors.bg0      , nil                              )
Group.new('Pmenu'            , colors.fg         , colors.bg2      , nil                              )
Group.new('PmenuSbar'        , colors.none       , colors.bg2      , nil                              )
Group.new('PmenuSel'         , colors.bg0        , colors.bg_blue  , nil                              )
Group.new('PmenuThumb'       , colors.none       , colors.grey     , nil                              )
Group.new('Question'         , colors.yellow     , colors.none     , nil                              )
Group.new('QuickFixLine'     , colors.blue       , colors.none     , styles.bold                      )
Group.new('Search'           , colors.bg0        , colors.bg_green , nil                              )
Group.new('SignColumn'       , colors.fg         , colors.bg1      , nil                              )
Group.new('SpecialKey'       , colors.bg4        , colors.none     , nil                              )
Group.new('SpellBad'         , colors.red        , colors.none     , styles.undercurl + colors.red    )
Group.new('SpellCap'         , colors.yellow     , colors.none     , styles.undercurl + colors.yellow )
Group.new('SpellLocal'       , colors.blue       , colors.none     , styles.undercurl + colors.blue   )
Group.new('SpellRare'        , colors.purple     , colors.none     , styles.undercurl + colors.purple )
Group.new('StatusLine'       , colors.fg         , colors.bg3      , nil                              )
Group.new('StatusLineNC'     , colors.grey       , colors.bg1      , nil                              )
Group.new('StatusLineTerm'   , colors.fg         , colors.bg3      , nil                              )
Group.new('StatusLineTermNC' , colors.grey       , colors.bg1      , nil                              )
Group.new('TabLine'          , colors.fg         , colors.bg4      , nil                              )
Group.new('TabLineFill'      , colors.grey       , colors.bg1      , nil                              )
Group.new('TabLineSel'       , colors.bg0        , colors.bg_red   , nil                              )
Group.new('Terminal'         , colors.fg         , colors.bg0      , nil                              )
Group.new('ToolbarButton'    , colors.bg0        , colors.bg_blue  , nil                              )
Group.new('ToolbarLine'      , colors.fg         , colors.bg2      , nil                              )
Group.new('VertSplit'        , colors.grey       , colors.none     , nil                              )
Group.new('Visual'           , colors.none       , colors.bg3      , nil                              )
Group.new('VisualNOS'        , colors.none       , colors.bg3      , styles.underline                 )
Group.new('WarningMsg'       , colors.yellow     , colors.none     , styles.bold                      )
Group.new('Whitespace'       , colors.bg4        , colors.none     , nil                              )
Group.new('WildMenu'         , colors.bg0        , colors.bg_blue  , nil                              )
Group.new('debugBreakpoint'  , colors.bg0        , colors.red      , nil                              )
Group.new('debugPC'          , colors.bg0        , colors.green    , nil                              )
