local inherit = require('cassiopeia.utils').Inherit
local c = require('cassiopeia.utils').colors
local s = require('cassiopeia.utils').styles

-- https://github.com/neoclide/coc.nvim
inherit('CocCodeLens'                  , 'Gray'                     )
inherit('CocErrorFloat'                , 'Red'        , nil , c.bg2 )
inherit('CocErrorHighlight'            , 'Gray'                     )
inherit('CocErrorSign'                 , 'Gray'                     )
inherit('CocErrorVirtualText'          , 'Gray'                     )
inherit('CocExplorerBufferBufname'     , 'Gray'                     )
inherit('CocExplorerBufferBufnr'       , 'Yellow'                   )
inherit('CocExplorerBufferExpandIcon'  , 'Blue'                     )
inherit('CocExplorerBufferFullpath'    , 'Gray'                     )
inherit('CocExplorerBufferModified'    , 'Red'                      )
inherit('CocExplorerBufferNameVisible' , 'Green'                    )
inherit('CocExplorerBufferRoot'        , 'Red'                      )
inherit('CocExplorerFileDirectory'     , 'Green'                    )
inherit('CocExplorerFileExpandIcon'    , 'Blue'                     )
inherit('CocExplorerFileFullpath'      , 'Gray'                     )
inherit('CocExplorerFileGitStage'      , 'Blue'                     )
inherit('CocExplorerFileGitUnstage'    , 'Yellow'                   )
inherit('CocExplorerFileRoot'          , 'Red'                      )
inherit('CocExplorerFileRootName'      , 'Orange'                   )
inherit('CocExplorerFileSize'          , 'Blue'                     )
inherit('CocExplorerTimeAccessed'      , 'Purple'                   )
inherit('CocExplorerTimeCreated'       , 'Purple'                   )
inherit('CocExplorerTimeModified'      , 'Purple'                   )
inherit('CocFloating'                  , 'Pmenu'                    )
inherit('CocGitAddedSign'              , 'Green'      , nil , c.bg1 )
inherit('CocGitChangeRemovedSign'      , 'Purple'     , nil , c.bg1 )
inherit('CocGitChangedSign'            , 'Blue'       , nil , c.bg1 )
inherit('CocGitRemovedSign'            , 'Red'        , nil , c.bg1 )
inherit('CocGitTopRemovedSign'         , 'Red'        , nil , c.bg1 )
inherit('CocHighlightText'             , 'None'       , nil , c.bg1 )
inherit('CocHintFloat'                 , 'Green'      , nil , c.bg2 )
inherit('CocHintHighlight'             , 'Undercurled'              )
inherit('CocHintSign'                  , 'Purple'     , nil , c.bg1 )
inherit('CocHintVirtualText'           , 'Gray'                     )
inherit('CocHoverRange'                , 'Underlined' , s.bold      )
inherit('CocInfoFloat'                 , 'Blue'       , nil , c.bg2 )
inherit('CocInfoHighlight'             , 'Gray'                     )
inherit('CocInfoSign'                  , 'Gray'                     )
inherit('CocInfoVirtualText'           , 'Gray'                     )
inherit('CocWarningFloat'              , 'Yellow'     , nil , c.bg2 )
inherit('CocWarningHighlight'          , 'Gray'                     )
inherit('CocWarningSign'               , 'Gray'                     )
inherit('CocWarningVirtualText'        , 'Gray'                     )
