local Group = require('cassiopeia.utils').Group
local g = require('cassiopeia.utils').g
local c = require('cassiopeia.utils').c
local s = require('cassiopeia.utils').s

-- https://github.com/neoclide/coc.nvim
Group.new('CocCodeLens'                  , g.Grey                  , g.Grey                  , g.Grey                  )
Group.new('CocErrorFloat'                , c.red                   , c.bg2                   , nil                     )
Group.new('CocErrorHighlight'            , g.ALEError              , g.ALEError              , g.ALEError              )
Group.new('CocErrorSign'                 , g.ALEErrorSign          , g.ALEErrorSign          , g.ALEErrorSign          )
Group.new('CocErrorVirtualText'          , g.ALEVirtualTextError   , g.ALEVirtualTextError   , g.ALEVirtualTextError   )
Group.new('CocExplorerBufferBufname'     , g.Grey                  , g.Grey                  , g.Grey                  )
Group.new('CocExplorerBufferBufnr'       , g.Yellow                , g.Yellow                , g.Yellow                )
Group.new('CocExplorerBufferExpandIcon'  , g.Blue                  , g.Blue                  , g.Blue                  )
Group.new('CocExplorerBufferFullpath'    , g.Grey                  , g.Grey                  , g.Grey                  )
Group.new('CocExplorerBufferModified'    , g.Red                   , g.Red                   , g.Red                   )
Group.new('CocExplorerBufferNameVisible' , g.Green                 , g.Green                 , g.Green                 )
Group.new('CocExplorerBufferRoot'        , g.Red                   , g.Red                   , g.Red                   )
Group.new('CocExplorerFileDirectory'     , g.Green                 , g.Green                 , g.Green                 )
Group.new('CocExplorerFileExpandIcon'    , g.Blue                  , g.Blue                  , g.Blue                  )
Group.new('CocExplorerFileFullpath'      , g.Grey                  , g.Grey                  , g.Grey                  )
Group.new('CocExplorerFileGitStage'      , g.Blue                  , g.Blue                  , g.Blue                  )
Group.new('CocExplorerFileGitUnstage'    , g.Yellow                , g.Yellow                , g.Yellow                )
Group.new('CocExplorerFileRoot'          , g.Red                   , g.Red                   , g.Red                   )
Group.new('CocExplorerFileRootName'      , g.Orange                , g.Orange                , g.Orange                )
Group.new('CocExplorerFileSize'          , g.Blue                  , g.Blue                  , g.Blue                  )
Group.new('CocExplorerTimeAccessed'      , g.Purple                , g.Purple                , g.Purple                )
Group.new('CocExplorerTimeCreated'       , g.Purple                , g.Purple                , g.Purple                )
Group.new('CocExplorerTimeModified'      , g.Purple                , g.Purple                , g.Purple                )
Group.new('CocGitAddedSign'              , g.GitGutterAdd          , g.GitGutterAdd          , g.GitGutterAdd          )
Group.new('CocGitChangeRemovedSign'      , g.GitGutterChangeDelete , g.GitGutterChangeDelete , g.GitGutterChangeDelete )
Group.new('CocGitChangedSign'            , g.GitGutterChange       , g.GitGutterChange       , g.GitGutterChange       )
Group.new('CocGitRemovedSign'            , g.GitGutterDelete       , g.GitGutterDelete       , g.GitGutterDelete       )
Group.new('CocGitTopRemovedSign'         , g.GitGutterDelete       , g.GitGutterDelete       , g.GitGutterDelete       )
Group.new('CocHighlightText'             , c.none                  , c.none                  , s.italic                )
Group.new('CocHintFloat'                 , c.green                 , c.bg2                   , nil                     )
Group.new('CocHintHighlight'             , c.none                  , c.none                  , s.undercurl             )
Group.new('CocHintSign'                  , c.purple                , c.bg1                   , nil                     )
Group.new('CocHintSign'                  , g.Label                 , g.Label                 , g.Label                 )
Group.new('CocHintVirtualText'           , g.ALEVirtualTextInfo    , g.ALEVirtualTextInfo    , g.ALEVirtualTextInfo    )
Group.new('CocHoverRange'                , c.none                  , c.none                  , s.bold + s.underline    )
Group.new('CocInfoFloat'                 , c.blue                  , c.bg2                   , nil                     )
Group.new('CocInfoHighlight'             , g.ALEInfo               , g.ALEInfo               , g.ALEInfo               )
Group.new('CocInfoSign'                  , g.ALEInfoSign           , g.ALEInfoSign           , g.ALEInfoSign           )
Group.new('CocInfoVirtualText'           , g.ALEVirtualTextInfo    , g.ALEVirtualTextInfo    , g.ALEVirtualTextInfo    )
Group.new('CocWarningFloat'              , c.yellow                , c.bg2                   , nil                     )
Group.new('CocWarningHighlight'          , g.ALEWarning            , g.ALEWarning            , g.ALEWarning            )
Group.new('CocWarningSign'               , g.ALEWarningSign        , g.ALEWarningSign        , g.ALEWarningSign        )
Group.new('CocWarningVirtualText'        , g.ALEVirtualTextWarning , g.ALEVirtualTextWarning , g.ALEVirtualTextWarning )
