local c = require('cassiopeia.palette')
local Highlight = require('cassiopeia.utils').Highlight
local Link = require('cassiopeia.utils').Link

-- https://github.com/neoclide/coc.nvim
Link('CocCodeLens'                 , 'Gray'        )
Link('CocErrorHighlight'           , 'Gray'        )
Link('CocErrorSign'                , 'Gray'        )
Link('CocErrorVirtualText'         , 'Gray'        )
Link('CocExplorerBufferBufname'    , 'Gray'        )
Link('CocExplorerBufferBufnr'      , 'Yellow'      )
Link('CocExplorerBufferExpandIcon' , 'Blue'        )
Link('CocExplorerBufferFullpath'   , 'Gray'        )
Link('CocExplorerBufferModified'   , 'Red'         )
Link('CocExplorerBufferNameVisible', 'Green'       )
Link('CocExplorerBufferRoot'       , 'Red'         )
Link('CocExplorerFileDirectory'    , 'Green'       )
Link('CocExplorerFileExpandIcon'   , 'Blue'        )
Link('CocExplorerFileFullpath'     , 'Gray'        )
Link('CocExplorerFileGitStage'     , 'Blue'        )
Link('CocExplorerFileGitUnstage'   , 'Yellow'      )
Link('CocExplorerFileRoot'         , 'Red'         )
Link('CocExplorerFileRootName'     , 'Orange'      )
Link('CocExplorerFileSize'         , 'Blue'        )
Link('CocExplorerTimeAccessed'     , 'Purple'      )
Link('CocExplorerTimeCreated'      , 'Purple'      )
Link('CocExplorerTimeModified'     , 'Purple'      )
Link('CocFloating'                 , 'Pmenu'       )
Link('CocInfoHighlight'            , 'Gray'        )
Link('CocHintHighlight'            , 'Undercurled' )
Link('CocInfoSign'                 , 'Gray'        )
Link('CocInfoVirtualText'          , 'Gray'        )
Link('CocWarningHighlight'         , 'Gray'        )
Link('CocWarningSign'              , 'Gray'        )
Link('CocWarningVirtualText'       , 'Gray'        )
Link('CocHintVirtualText'          , 'Gray'        )
Link('CocHoverRange'               , 'Underlined'  )

Highlight('CocErrorFloat'          , {fg = c.red   , bg = c.bg2 })
Highlight('CocGitAddedSign'        , {fg = c.green , bg = c.bg1 })
Highlight('CocGitChangeRemovedSign', {fg = c.purple, bg = c.bg1 })
Highlight('CocGitChangedSign'      , {fg = c.blue  , bg = c.bg1 })
Highlight('CocGitRemovedSign'      , {fg = c.red   , bg = c.bg1 })
Highlight('CocGitTopRemovedSign'   , {fg = c.red   , bg = c.bg1 })
Highlight('CocHighlightText'       , {fg = c.none  , bg = c.bg1 })
Highlight('CocHintFloat'           , {fg = c.green , bg = c.bg2 })
Highlight('CocHintSign'            , {fg = c.purple, bg = c.bg1 })
Highlight('CocWarningFloat'        , {fg = c.yellow, bg = c.bg2 })
Highlight('CocInfoFloat'           , {fg = c.blue  , bg = c.bg2 })
