local colors = require('cassiopeia.utils').colors
local styles = require('cassiopeia.utils').styles
local Group = require('cassiopeia.utils').Group
local groups = require('cassiopeia.utils').groups

Group.new('Normal', colors.fg, colors.bg0, nil)
Group.new('Terminal', colors.fg, colors.bg0, nil)
Group.new('EndOfBuffer', colors.bg0, colors.bg0, nil)
Group.new('FoldColumn', colors.grey, colors.bg1, nil)
Group.new('Folded', colors.grey, colors.bg1, nil)
Group.new('SignColumn', colors.fg, colors.bg1, nil)
Group.new('ToolbarLine', colors.fg, colors.bg2, nil)
Group.new('ColorColumn', colors.none, colors.bg1, nil)
Group.new('Conceal', colors.grey, colors.none, nil)
Group.new('Cursor', colors.none, colors.none, styles.reverse)
Group.new('vCursor', groups.Cursor, groups.Cursor, groups.Cursor)
Group.new('iCursor', groups.Cursor, groups.Cursor, groups.Cursor)
Group.new('lCursor', groups.Cursor, groups.Cursor, groups.Cursor)
Group.new('CursorIM', groups.Cursor, groups.Cursor, groups.Cursor)
Group.new('CursorColumn', colors.none, colors.bg1, nil)
Group.new('CursorLine', colors.none, colors.bg1, nil)
Group.new('LineNr', colors.grey, colors.none, nil)
Group.new('CursorLineNr', colors.fg, colors.bg1, nil)
Group.new('DiffAdd', colors.none, colors.diff_green, nil)
Group.new('DiffChange', colors.none, colors.diff_blue, nil)
Group.new('DiffDelete', colors.none, colors.diff_red, nil)
Group.new('DiffText', colors.none, colors.none, styles.reverse)
Group.new('Directory', colors.green, colors.none, nil)
Group.new('ErrorMsg', colors.red, colors.none, styles.bold + styles.underline)
Group.new('WarningMsg', colors.yellow, colors.none, styles.bold)
Group.new('ModeMsg', colors.fg, colors.none, styles.bold)
Group.new('MoreMsg', colors.blue, colors.none, styles.bold)
Group.new('IncSearch', colors.bg0, colors.bg_red, nil)
Group.new('Search', colors.bg0, colors.bg_green, nil)
Group.new('MatchParen', colors.none, colors.bg4, nil)
Group.new('NonText', colors.bg4, colors.none, nil)
Group.new('Whitespace', colors.bg4, colors.none, nil)
Group.new('SpecialKey', colors.bg4, colors.none, nil)
Group.new('Pmenu', colors.fg, colors.bg2, nil)
Group.new('PmenuSbar', colors.none, colors.bg2, nil)
Group.new('PmenuSel', colors.bg0, colors.bg_blue, nil)
Group.new('WildMenu', colors.bg0, colors.bg_blue, nil)
Group.new('PmenuThumb', colors.none, colors.grey, nil)
Group.new('Question', colors.yellow, colors.none, nil)
Group.new('SpellBad', colors.red, colors.none, styles.undercurl)
Group.new('SpellCap', colors.yellow, colors.none, styles.undercurl)
Group.new('SpellLocal', colors.blue, colors.none, styles.undercurl)
Group.new('SpellRare', colors.purple, colors.none, styles.undercurl)
Group.new('StatusLine', colors.fg, colors.bg3, nil)
Group.new('StatusLineTerm', colors.fg, colors.bg3, nil)
Group.new('StatusLineNC', colors.grey, colors.bg1, nil)
Group.new('StatusLineTermNC', colors.grey, colors.bg1, nil)
Group.new('TabLine', colors.fg, colors.bg4, nil)
Group.new('TabLineFill', colors.grey, colors.bg1, nil)
Group.new('TabLineSel', colors.bg0, colors.bg_red, nil)
Group.new('VertSplit', colors.black, colors.none, nil)
Group.new('Visual', colors.none, colors.bg3, nil)
Group.new('VisualNOS', colors.none, colors.bg3, styles.underline)
Group.new('QuickFixLine', colors.blue, colors.none, styles.bold)
Group.new('Debug', colors.yellow, colors.none, nil)
Group.new('debugPC', colors.bg0, colors.green, nil)
Group.new('debugBreakpoint', colors.bg0, colors.red, nil)
Group.new('ToolbarButton', colors.bg0, colors.bg_blue, nil)
Group.new('healthError', groups.Red, groups.Red, groups.Red)
Group.new('healthSuccess', groups.Green, groups.Green, groups.Green)
Group.new('healthWarning', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('LspDiagnosticsError', groups.Grey, groups.Grey, groups.Grey)
Group.new('LspDiagnosticsWarning', groups.Grey, groups.Grey, groups.Grey)
Group.new('LspDiagnosticsInformation', groups.Grey, groups.Grey, groups.Grey)
Group.new('LspDiagnosticsHint', groups.Grey, groups.Grey, groups.Grey)
Group.new('LspReferenceText', groups.CocHighlightText, groups.CocHighlightText, groups.CocHighlightText)
Group.new('LspReferenceRead', groups.CocHighlightText, groups.CocHighlightText, groups.CocHighlightText)
Group.new('LspReferenceWrite', groups.CocHighlightText, groups.CocHighlightText, groups.CocHighlightText)
Group.new('Type', colors.blue, colors.none, styles.italic)
Group.new('Structure', colors.blue, colors.none, styles.italic)
Group.new('StorageClass', colors.blue, colors.none, styles.italic)
Group.new('Identifier', colors.orange, colors.none, styles.italic)
Group.new('Constant', colors.orange, colors.none, styles.italic)
Group.new('Keyword', colors.red, colors.none, styles.italic)
Group.new('Conditional', colors.red, colors.none, styles.italic)
Group.new('Repeat', colors.red, colors.none, styles.italic)
Group.new('Boolean', colors.purple, colors.none, styles.italic)
Group.new('Statement', colors.red, colors.none, styles.italic)
Group.new('PreProc', colors.red, colors.none, nil)
Group.new('PreCondit', colors.red, colors.none, nil)
Group.new('Include', colors.red, colors.none, nil)
Group.new('Define', colors.red, colors.none, nil)
Group.new('Typedef', colors.red, colors.none, nil)
Group.new('Exception', colors.red, colors.none, nil)
Group.new('Macro', colors.purple, colors.none, nil)
Group.new('Error', colors.red, colors.none, nil)
Group.new('Label', colors.purple, colors.none, nil)
Group.new('Special', colors.purple, colors.none, nil)
Group.new('SpecialChar', colors.purple, colors.none, nil)
Group.new('String', colors.yellow, colors.none, nil)
Group.new('Character', colors.yellow, colors.none, nil)
Group.new('Number', colors.purple, colors.none, nil)
Group.new('Float', colors.purple, colors.none, nil)
Group.new('Function', colors.orange, colors.none, nil)
Group.new('Operator', colors.red, colors.none, nil)
Group.new('Title', colors.red, colors.none, styles.bold)
Group.new('Tag', colors.orange, colors.none, nil)
Group.new('Delimiter', colors.fg, colors.none, nil)
Group.new('Comment', colors.grey, colors.none, styles.italic)
Group.new('SpecialComment', colors.grey, colors.none, styles.italic)
Group.new('Todo', colors.blue, colors.none, styles.underline)
Group.new('Ignore', colors.grey, colors.none, nil)
Group.new('Underlined', colors.none, colors.none, styles.underline)
Group.new('Fg', colors.fg, colors.none, nil)
Group.new('Grey', colors.grey, colors.none, nil)
Group.new('Red', colors.red, colors.none, nil)
Group.new('Orange', colors.orange, colors.none, nil)
Group.new('Yellow', colors.yellow, colors.none, nil)
Group.new('Green', colors.green, colors.none, nil)
Group.new('Blue', colors.blue, colors.none, nil)
Group.new('Purple', colors.purple, colors.none, nil)
Group.new('RedItalic', colors.red, colors.none, styles.italic)
Group.new('PurpleItalic', colors.purple, colors.none, styles.italic)
Group.new('GreenItalic', colors.green, colors.none, styles.italic)
Group.new('YellowItalic', colors.yellow, colors.none, styles.italic)
Group.new('BlueItalic', colors.blue, colors.none, styles.italic)
Group.new('OrangeItalic', colors.orange, colors.none, styles.italic)
Group.new('markdownH1', colors.red, colors.none, styles.bold)
Group.new('markdownH2', colors.orange, colors.none, styles.bold)
Group.new('markdownH3', colors.yellow, colors.none, styles.bold)
Group.new('markdownH4', colors.green, colors.none, styles.bold)
Group.new('markdownH5', colors.blue, colors.none, styles.bold)
Group.new('markdownH6', colors.purple, colors.none, styles.bold)
Group.new('markdownUrl', colors.blue, colors.none, styles.underline)
Group.new('markdownItalic', colors.none, colors.none, styles.italic)
Group.new('markdownBold', colors.none, colors.none, styles.bold)
Group.new('markdownItalicDelimiter', colors.grey, colors.none, styles.italic)
Group.new('markdownCode', groups.Green, groups.Green, groups.Green)
Group.new('markdownCodeBlock', groups.Green, groups.Green, groups.Green)
Group.new('markdownCodeDelimiter', groups.Green, groups.Green, groups.Green)
Group.new('markdownBlockquote', groups.Grey, groups.Grey, groups.Grey)
Group.new('markdownListMarker', groups.Red, groups.Red, groups.Red)
Group.new('markdownOrderedListMarker', groups.Red, groups.Red, groups.Red)
Group.new('markdownRule', groups.Purple, groups.Purple, groups.Purple)
Group.new('markdownHeadingRule', groups.Grey, groups.Grey, groups.Grey)
Group.new('markdownUrlDelimiter', groups.Grey, groups.Grey, groups.Grey)
Group.new('markdownLinkDelimiter', groups.Grey, groups.Grey, groups.Grey)
Group.new('markdownLinkTextDelimiter', groups.Grey, groups.Grey, groups.Grey)
Group.new('markdownHeadingDelimiter', groups.Grey, groups.Grey, groups.Grey)
Group.new('markdownLinkText', groups.Red, groups.Red, groups.Red)
Group.new('markdownUrlTitleDelimiter', groups.Green, groups.Green, groups.Green)
Group.new('markdownIdDeclaration', groups.markdownLinkText, groups.markdownLinkText, groups.markdownLinkText)
Group.new('markdownBoldDelimiter', groups.Grey, groups.Grey, groups.Grey)
Group.new('markdownId', groups.Yellow, groups.Yellow, groups.Yellow)


Group.new('mkdURL', colors.blue, colors.none, styles.underline)
Group.new('mkdInlineURL', colors.blue, colors.none, styles.underline)
Group.new('mkdItalic', colors.grey, colors.none, styles.italic)
Group.new('mkdCodeDelimiter', groups.Green, groups.Green, groups.Green)
Group.new('mkdBold', groups.Grey, groups.Grey, groups.Grey)
Group.new('mkdLink', groups.Red, groups.Red, groups.Red)
Group.new('mkdHeading', groups.Grey, groups.Grey, groups.Grey)
Group.new('mkdListItem', groups.Red, groups.Red, groups.Red)
Group.new('mkdRule', groups.Purple, groups.Purple, groups.Purple)
Group.new('mkdDelimiter', groups.Grey, groups.Grey, groups.Grey)
Group.new('mkdId', groups.Yellow, groups.Yellow, groups.Yellow)




Group.new('rstStandaloneHyperlink', colors.purple, colors.none, styles.underline)
Group.new('rstEmphasis', colors.none, colors.none, styles.italic)
Group.new('rstStrongEmphasis', colors.none, colors.none, styles.bold)
Group.new('rstStandaloneHyperlink', colors.blue, colors.none, styles.underline)
Group.new('rstHyperlinkTarget', colors.blue, colors.none, styles.underline)
Group.new('rstSubstitutionReference', groups.Blue, groups.Blue, groups.Blue)
Group.new('rstInterpretedTextOrHyperlinkReference', groups.Green, groups.Green, groups.Green)
Group.new('rstTableLines', groups.Grey, groups.Grey, groups.Grey)
Group.new('rstInlineLiteral', groups.Green, groups.Green, groups.Green)
Group.new('rstLiteralBlock', groups.Green, groups.Green, groups.Green)
Group.new('rstQuotedLiteralBlock', groups.Green, groups.Green, groups.Green)




Group.new('texStatement', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('texOnlyMath', groups.Grey, groups.Grey, groups.Grey)
Group.new('texDefName', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('texNewCmd', groups.Orange, groups.Orange, groups.Orange)
Group.new('texCmdName', groups.Blue, groups.Blue, groups.Blue)
Group.new('texBeginEnd', groups.Red, groups.Red, groups.Red)
Group.new('texBeginEndName', groups.Green, groups.Green, groups.Green)
Group.new('texDocType', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('texDocTypeArgs', groups.Orange, groups.Orange, groups.Orange)
Group.new('texInputFile', groups.Green, groups.Green, groups.Green)




Group.new('htmlH1', colors.red, colors.none, styles.bold)
Group.new('htmlH2', colors.orange, colors.none, styles.bold)
Group.new('htmlH3', colors.yellow, colors.none, styles.bold)
Group.new('htmlH4', colors.green, colors.none, styles.bold)
Group.new('htmlH5', colors.blue, colors.none, styles.bold)
Group.new('htmlH6', colors.purple, colors.none, styles.bold)
Group.new('htmlLink', colors.none, colors.none, styles.underline)
Group.new('htmlBold', colors.none, colors.none, styles.bold)
Group.new('htmlBoldUnderline', colors.none, colors.none, styles.bold + styles.underline)
Group.new('htmlBoldItalic', colors.none, colors.none, styles.bold + styles.italic)
Group.new('htmlBoldUnderlineItalic', colors.none, colors.none, styles.bold + styles.underline + styles.italic)
Group.new('htmlUnderline', colors.none, colors.none, styles.underline)
Group.new('htmlUnderlineItalic', colors.none, colors.none, styles.underline + styles.italic)
Group.new('htmlItalic', colors.none, colors.none, styles.italic)
Group.new('htmlTag', groups.Green, groups.Green, groups.Green)
Group.new('htmlEndTag', groups.Blue, groups.Blue, groups.Blue)
Group.new('htmlTagN', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('htmlTagName', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('htmlArg', groups.Blue, groups.Blue, groups.Blue)
Group.new('htmlScriptTag', groups.Purple, groups.Purple, groups.Purple)
Group.new('htmlSpecialTagName', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('htmlString', groups.Green, groups.Green, groups.Green)




Group.new('xmlTag', groups.Green, groups.Green, groups.Green)
Group.new('xmlEndTag', groups.Blue, groups.Blue, groups.Blue)
Group.new('xmlTagName', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('xmlEqual', groups.Orange, groups.Orange, groups.Orange)
Group.new('xmlAttrib', groups.Blue, groups.Blue, groups.Blue)
Group.new('xmlEntity', groups.Red, groups.Red, groups.Red)
Group.new('xmlEntityPunct', groups.Red, groups.Red, groups.Red)
Group.new('xmlDocTypeDecl', groups.Grey, groups.Grey, groups.Grey)
Group.new('xmlDocTypeKeyword', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('xmlCdataStart', groups.Grey, groups.Grey, groups.Grey)
Group.new('xmlCdataCdata', groups.Purple, groups.Purple, groups.Purple)
Group.new('xmlString', groups.Green, groups.Green, groups.Green)




Group.new('cssStringQ', groups.Green, groups.Green, groups.Green)
Group.new('cssStringQQ', groups.Green, groups.Green, groups.Green)
Group.new('cssAttrComma', groups.Grey, groups.Grey, groups.Grey)
Group.new('cssBraces', groups.Grey, groups.Grey, groups.Grey)
Group.new('cssTagName', groups.Purple, groups.Purple, groups.Purple)
Group.new('cssClassNameDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('cssClassName', groups.Red, groups.Red, groups.Red)
Group.new('cssFunctionName', groups.Orange, groups.Orange, groups.Orange)
Group.new('cssAttr', groups.Green, groups.Green, groups.Green)
Group.new('cssCommonAttr', groups.Green, groups.Green, groups.Green)
Group.new('cssProp', groups.Blue, groups.Blue, groups.Blue)
Group.new('cssPseudoClassId', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('cssPseudoClassFn', groups.Green, groups.Green, groups.Green)
Group.new('cssPseudoClass', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('cssImportant', groups.Red, groups.Red, groups.Red)
Group.new('cssSelectorOp', groups.Orange, groups.Orange, groups.Orange)
Group.new('cssSelectorOp2', groups.Orange, groups.Orange, groups.Orange)
Group.new('cssColor', groups.Green, groups.Green, groups.Green)
Group.new('cssUnitDecorators', groups.Orange, groups.Orange, groups.Orange)
Group.new('cssValueLength', groups.Green, groups.Green, groups.Green)
Group.new('cssValueInteger', groups.Green, groups.Green, groups.Green)
Group.new('cssValueNumber', groups.Green, groups.Green, groups.Green)
Group.new('cssValueAngle', groups.Green, groups.Green, groups.Green)
Group.new('cssValueTime', groups.Green, groups.Green, groups.Green)
Group.new('cssValueFrequency', groups.Green, groups.Green, groups.Green)
Group.new('cssVendor', groups.Grey, groups.Grey, groups.Grey)
Group.new('cssNoise', groups.Grey, groups.Grey, groups.Grey)




Group.new('scssMixinName', groups.Orange, groups.Orange, groups.Orange)
Group.new('scssSelectorChar', groups.Orange, groups.Orange, groups.Orange)
Group.new('scssSelectorName', groups.Red, groups.Red, groups.Red)
Group.new('scssInterpolationDelimiter', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('scssVariableValue', groups.Green, groups.Green, groups.Green)
Group.new('scssNull', groups.Purple, groups.Purple, groups.Purple)
Group.new('scssBoolean', groups.Purple, groups.Purple, groups.Purple)
Group.new('scssVariableAssignment', groups.Grey, groups.Grey, groups.Grey)
Group.new('scssAttribute', groups.Green, groups.Green, groups.Green)
Group.new('scssFunctionName', groups.Orange, groups.Orange, groups.Orange)
Group.new('scssVariable', groups.Fg, groups.Fg, groups.Fg)
Group.new('scssAmpersand', groups.Purple, groups.Purple, groups.Purple)




Group.new('lessMixinChar', groups.Grey, groups.Grey, groups.Grey)
Group.new('lessClass', groups.Red, groups.Red, groups.Red)
Group.new('lessFunction', groups.Orange, groups.Orange, groups.Orange)




Group.new('javaScriptNull', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('javaScriptIdentifier', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('javaScriptParens', groups.Fg, groups.Fg, groups.Fg)
Group.new('javaScriptBraces', groups.Fg, groups.Fg, groups.Fg)
Group.new('javaScriptNumber', groups.Purple, groups.Purple, groups.Purple)
Group.new('javaScriptLabel', groups.Red, groups.Red, groups.Red)
Group.new('javaScriptGlobal', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('javaScriptMessage', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)


Group.new('jsNoise', groups.Fg, groups.Fg, groups.Fg)
Group.new('Noise', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsParens', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsBrackets', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsObjectBraces', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsThis', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('jsUndefined', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('jsNull', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('jsNan', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('jsSuper', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('jsPrototype', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('jsFunction', groups.Red, groups.Red, groups.Red)
Group.new('jsGlobalNodeObjects', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('jsGlobalObjects', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('jsArrowFunction', groups.Red, groups.Red, groups.Red)
Group.new('jsArrowFuncArgs', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsFuncArgs', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsObjectProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsVariableDef', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsObjectKey', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsParen', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsParenIfElse', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsParenRepeat', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsParenSwitch', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsParenCatch', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsBracket', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsObjectValue', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsDestructuringBlock', groups.Fg, groups.Fg, groups.Fg)
Group.new('jsBlockLabel', groups.Purple, groups.Purple, groups.Purple)
Group.new('jsFunctionKey', groups.Green, groups.Green, groups.Green)
Group.new('jsClassDefinition', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('jsDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('jsSpreadExpression', groups.Purple, groups.Purple, groups.Purple)
Group.new('jsSpreadOperator', groups.Green, groups.Green, groups.Green)
Group.new('jsModuleKeyword', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('jsTemplateExpression', groups.Purple, groups.Purple, groups.Purple)
Group.new('jsTemplateBraces', groups.Purple, groups.Purple, groups.Purple)
Group.new('jsClassMethodType', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('jsExceptions', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)


Group.new('javascriptOpSymbol', groups.Red, groups.Red, groups.Red)
Group.new('javascriptOpSymbols', groups.Red, groups.Red, groups.Red)
Group.new('javascriptIdentifierName', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptVariable', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('javascriptObjectLabel', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptPropertyNameString', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptFuncArg', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptObjectLiteral', groups.Green, groups.Green, groups.Green)
Group.new('javascriptIdentifier', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('javascriptArrowFunc', groups.Red, groups.Red, groups.Red)
Group.new('javascriptTemplate', groups.Purple, groups.Purple, groups.Purple)
Group.new('javascriptTemplateSubstitution', groups.Purple, groups.Purple, groups.Purple)
Group.new('javascriptTemplateSB', groups.Purple, groups.Purple, groups.Purple)
Group.new('javascriptNodeGlobal', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('javascriptDocTags', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('javascriptDocNotation', groups.Blue, groups.Blue, groups.Blue)
Group.new('javascriptClassSuper', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('javascriptClassName', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('javascriptClassSuperName', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('javascriptOperator', groups.Red, groups.Red, groups.Red)
Group.new('javascriptBrackets', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptBraces', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptLabel', groups.Purple, groups.Purple, groups.Purple)
Group.new('javascriptEndColons', groups.Grey, groups.Grey, groups.Grey)
Group.new('javascriptObjectLabelColon', groups.Grey, groups.Grey, groups.Grey)
Group.new('javascriptDotNotation', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalArrayDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalBigIntDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalDateDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalJSONDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalMathDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalNumberDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalObjectDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalPromiseDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalRegExpDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalStringDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalSymbolDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptGlobalURLDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('javascriptMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptMethodName', groups.Green, groups.Green, groups.Green)
Group.new('javascriptObjectMethodName', groups.Green, groups.Green, groups.Green)
Group.new('javascriptGlobalMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptDOMStorageMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptFileMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptFileReaderMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptFileListMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptBlobMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptURLStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptNumberStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptNumberMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptDOMNodeMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptES6BigIntStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptBOMWindowMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptHeadersMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptRequestMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptResponseMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptES6SetMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptReflectMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptPaymentMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptPaymentResponseMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptTypedArrayStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptGeolocationMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptES6MapMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptServiceWorkerMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptCacheMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptFunctionMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptXHRMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptBOMNavigatorMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptServiceWorkerMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptDOMEventTargetMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptDOMEventMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptIntlMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptDOMDocMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptStringStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptStringMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptSymbolStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptRegExpMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptObjectStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptObjectMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptBOMLocationMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptJSONStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptGeneratorMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptEncodingMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptPromiseStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptPromiseMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptBOMHistoryMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptDOMFormMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptClipboardMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptTypedArrayStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptBroadcastMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptDateStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptDateMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptConsoleMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptArrayStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptArrayMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptMathStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptSubtleCryptoMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptCryptoMethod', groups.Green, groups.Green, groups.Green)
Group.new('javascriptProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptBOMWindowProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptDOMStorageProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptFileReaderProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptURLUtilsProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptNumberStaticProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptDOMNodeProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptRequestProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptResponseProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptES6SetProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptPaymentProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptPaymentResponseProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptPaymentAddressProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptPaymentShippingOptionProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptTypedArrayStaticProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptServiceWorkerProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptES6MapProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptRegExpStaticProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptRegExpProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptXHRProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptBOMNavigatorProp', groups.Green, groups.Green, groups.Green)
Group.new('javascriptDOMEventProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptBOMNetworkProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptDOMDocProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptSymbolStaticProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptSymbolProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptBOMLocationProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptEncodingProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptCryptoProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptBOMHistoryProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptDOMFormProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptDataViewProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptBroadcastProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('javascriptMathStaticProp', groups.Fg, groups.Fg, groups.Fg)




Group.new('jsxTagName', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('jsxOpenPunct', groups.Green, groups.Green, groups.Green)
Group.new('jsxClosePunct', groups.Blue, groups.Blue, groups.Blue)
Group.new('jsxEscapeJs', groups.Purple, groups.Purple, groups.Purple)
Group.new('jsxAttrib', groups.Blue, groups.Blue, groups.Blue)




Group.new('typescriptStorageClass', groups.Red, groups.Red, groups.Red)
Group.new('typescriptEndColons', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptSource', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptMessage', groups.Green, groups.Green, groups.Green)
Group.new('typescriptGlobalObjects', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptInterpolation', groups.Purple, groups.Purple, groups.Purple)
Group.new('typescriptInterpolationDelimiter', groups.Purple, groups.Purple, groups.Purple)
Group.new('typescriptBraces', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptParens', groups.Fg, groups.Fg, groups.Fg)


Group.new('typescriptMethodAccessor', groups.Red, groups.Red, groups.Red)
Group.new('typescriptVariable', groups.Red, groups.Red, groups.Red)
Group.new('typescriptVariableDeclaration', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptTypeReference', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptBraces', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptEnumKeyword', groups.Red, groups.Red, groups.Red)
Group.new('typescriptEnum', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptIdentifierName', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptCall', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptInterfaceName', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptEndColons', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptMember', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptMemberOptionality', groups.Red, groups.Red, groups.Red)
Group.new('typescriptObjectLabel', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptDefaultParam', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptArrowFunc', groups.Red, groups.Red, groups.Red)
Group.new('typescriptAbstract', groups.Red, groups.Red, groups.Red)
Group.new('typescriptObjectColon', groups.Grey, groups.Grey, groups.Grey)
Group.new('typescriptTypeAnnotation', groups.Grey, groups.Grey, groups.Grey)
Group.new('typescriptAssign', groups.Red, groups.Red, groups.Red)
Group.new('typescriptBinaryOp', groups.Red, groups.Red, groups.Red)
Group.new('typescriptUnaryOp', groups.Red, groups.Red, groups.Red)
Group.new('typescriptFuncComma', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptClassName', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptClassHeritage', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptInterfaceHeritage', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptIdentifier', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('typescriptGlobal', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptOperator', groups.Red, groups.Red, groups.Red)
Group.new('typescriptNodeGlobal', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptExport', groups.Red, groups.Red, groups.Red)
Group.new('typescriptImport', groups.Red, groups.Red, groups.Red)
Group.new('typescriptTypeParameter', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('typescriptReadonlyModifier', groups.Red, groups.Red, groups.Red)
Group.new('typescriptAccessibilityModifier', groups.Red, groups.Red, groups.Red)
Group.new('typescriptAmbientDeclaration', groups.Red, groups.Red, groups.Red)
Group.new('typescriptTemplateSubstitution', groups.Purple, groups.Purple, groups.Purple)
Group.new('typescriptTemplateSB', groups.Purple, groups.Purple, groups.Purple)
Group.new('typescriptExceptions', groups.Red, groups.Red, groups.Red)
Group.new('typescriptCastKeyword', groups.Red, groups.Red, groups.Red)
Group.new('typescriptOptionalMark', groups.Red, groups.Red, groups.Red)
Group.new('typescriptNull', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('typescriptMappedIn', groups.Red, groups.Red, groups.Red)
Group.new('typescriptFuncTypeArrow', groups.Red, groups.Red, groups.Red)
Group.new('typescriptTernaryOp', groups.Red, groups.Red, groups.Red)
Group.new('typescriptParenExp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptIndexExpr', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptDotNotation', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalNumberDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalStringDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalArrayDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalObjectDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalSymbolDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalMathDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalDateDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalJSONDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalRegExpDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalPromiseDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalURLDot', groups.Orange, groups.Orange, groups.Orange)
Group.new('typescriptGlobalMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptDOMStorageMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptFileMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptFileReaderMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptFileListMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptBlobMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptURLStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptNumberStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptNumberMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptDOMNodeMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptPaymentMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptPaymentResponseMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptHeadersMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptRequestMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptResponseMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptES6SetMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptReflectMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptBOMWindowMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptGeolocationMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptServiceWorkerMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptCacheMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptES6MapMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptFunctionMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptRegExpMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptXHRMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptBOMNavigatorMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptServiceWorkerMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptIntlMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptDOMEventTargetMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptDOMEventMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptDOMDocMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptStringStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptStringMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptSymbolStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptObjectStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptObjectMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptJSONStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptEncodingMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptBOMLocationMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptPromiseStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptPromiseMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptSubtleCryptoMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptCryptoMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptBOMHistoryMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptDOMFormMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptConsoleMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptDateStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptDateMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptArrayStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptArrayMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptMathStaticMethod', groups.Green, groups.Green, groups.Green)
Group.new('typescriptStringProperty', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptDOMStorageProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptFileReaderProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptURLUtilsProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptNumberStaticProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptDOMNodeProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptBOMWindowProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptRequestProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptResponseProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptPaymentProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptPaymentResponseProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptPaymentAddressProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptPaymentShippingOptionProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptES6SetProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptServiceWorkerProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptES6MapProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptRegExpStaticProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptRegExpProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptBOMNavigatorProp', groups.Green, groups.Green, groups.Green)
Group.new('typescriptXHRProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptDOMEventProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptDOMDocProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptBOMNetworkProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptSymbolStaticProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptEncodingProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptBOMLocationProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptCryptoProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptDOMFormProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptBOMHistoryProp', groups.Fg, groups.Fg, groups.Fg)
Group.new('typescriptMathStaticProp', groups.Fg, groups.Fg, groups.Fg)




Group.new('dartCoreClasses', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('dartTypeName', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('dartInterpolation', groups.Purple, groups.Purple, groups.Purple)
Group.new('dartTypeDef', groups.Red, groups.Red, groups.Red)
Group.new('dartClassDecl', groups.Red, groups.Red, groups.Red)
Group.new('dartLibrary', groups.Red, groups.Red, groups.Red)
Group.new('dartMetadata', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)




Group.new('cLabel', groups.Red, groups.Red, groups.Red)
Group.new('cppSTLnamespace', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('cppSTLtype', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('cppAccess', groups.Red, groups.Red, groups.Red)
Group.new('cppStructure', groups.Red, groups.Red, groups.Red)
Group.new('cppSTLios', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('cppSTLiterator', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('cppSTLexception', groups.Red, groups.Red, groups.Red)


Group.new('cppSTLVariable', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)


Group.new('Member', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('Variable', groups.Fg, groups.Fg, groups.Fg)
Group.new('Namespace', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('EnumConstant', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('chromaticaException', groups.Red, groups.Red, groups.Red)
Group.new('chromaticaCast', groups.Red, groups.Red, groups.Red)
Group.new('OperatorOverload', groups.Red, groups.Red, groups.Red)
Group.new('AccessQual', groups.Red, groups.Red, groups.Red)
Group.new('Linkage', groups.Red, groups.Red, groups.Red)
Group.new('AutoType', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)


Group.new('LspCxxHlSkippedRegion', groups.Grey, groups.Grey, groups.Grey)
Group.new('LspCxxHlSkippedRegionBeginEnd', groups.Red, groups.Red, groups.Red)
Group.new('LspCxxHlGroupEnumConstant', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('LspCxxHlGroupNamespace', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('LspCxxHlGroupMemberVariable', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)




Group.new('objcModuleImport', groups.Red, groups.Red, groups.Red)
Group.new('objcException', groups.Red, groups.Red, groups.Red)
Group.new('objcProtocolList', groups.Fg, groups.Fg, groups.Fg)
Group.new('objcDirective', groups.Red, groups.Red, groups.Red)
Group.new('objcPropertyAttribute', groups.Purple, groups.Purple, groups.Purple)
Group.new('objcHiddenArgument', groups.Fg, groups.Fg, groups.Fg)




Group.new('csUnspecifiedStatement', groups.Red, groups.Red, groups.Red)
Group.new('csStorage', groups.Red, groups.Red, groups.Red)
Group.new('csClass', groups.Red, groups.Red, groups.Red)
Group.new('csNewType', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('csContextualStatement', groups.Red, groups.Red, groups.Red)
Group.new('csInterpolationDelimiter', groups.Purple, groups.Purple, groups.Purple)
Group.new('csInterpolation', groups.Purple, groups.Purple, groups.Purple)
Group.new('csEndColon', groups.Fg, groups.Fg, groups.Fg)




Group.new('pythonBuiltin', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('pythonExceptions', groups.Red, groups.Red, groups.Red)
Group.new('pythonDecoratorName', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)


Group.new('pythonExClass', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('pythonClass', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('pythonBuiltinType', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('pythonBuiltinObj', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('pythonDottedName', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('pythonBuiltinFunc', groups.Green, groups.Green, groups.Green)
Group.new('pythonFunction', groups.Orange, groups.Orange, groups.Orange)
Group.new('pythonDecorator', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('pythonInclude', groups.Include, groups.Include, groups.Include)
Group.new('pythonImport', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('pythonOperator', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('pythonRawOperator', groups.Red, groups.Red, groups.Red)
Group.new('pythonConditional', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('pythonRepeat', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('pythonException', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('pythonNone', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('pythonCoding', groups.Grey, groups.Grey, groups.Grey)
Group.new('pythonDot', groups.Grey, groups.Grey, groups.Grey)


Group.new('semshiUnresolved', colors.orange, colors.none, styles.undercurl)
Group.new('semshiImported', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('semshiParameter', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('semshiParameterUnused', groups.Grey, groups.Grey, groups.Grey)
Group.new('semshiSelf', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('semshiGlobal', groups.Green, groups.Green, groups.Green)
Group.new('semshiBuiltin', groups.Green, groups.Green, groups.Green)
Group.new('semshiAttribute', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('semshiLocal', groups.Red, groups.Red, groups.Red)
Group.new('semshiFree', groups.Red, groups.Red, groups.Red)
Group.new('semshiSelected', groups.CocHighlightText, groups.CocHighlightText, groups.CocHighlightText)
Group.new('semshiErrorSign', groups.ALEErrorSign, groups.ALEErrorSign, groups.ALEErrorSign)
Group.new('semshiErrorChar', groups.ALEErrorSign, groups.ALEErrorSign, groups.ALEErrorSign)




Group.new('luaFunc', groups.Green, groups.Green, groups.Green)
Group.new('luaFunction', groups.Red, groups.Red, groups.Red)
Group.new('luaTable', groups.Fg, groups.Fg, groups.Fg)
Group.new('luaIn', groups.Red, groups.Red, groups.Red)


Group.new('luaFuncCall', groups.Green, groups.Green, groups.Green)
Group.new('luaLocal', groups.Red, groups.Red, groups.Red)
Group.new('luaSpecialValue', groups.Green, groups.Green, groups.Green)
Group.new('luaBraces', groups.Fg, groups.Fg, groups.Fg)
Group.new('luaBuiltIn', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('luaNoise', groups.Grey, groups.Grey, groups.Grey)
Group.new('luaLabel', groups.Purple, groups.Purple, groups.Purple)
Group.new('luaFuncTable', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('luaFuncArgName', groups.Fg, groups.Fg, groups.Fg)
Group.new('luaEllipsis', groups.Red, groups.Red, groups.Red)
Group.new('luaDocTag', groups.Green, groups.Green, groups.Green)




Group.new('javaClassDecl', groups.Red, groups.Red, groups.Red)
Group.new('javaMethodDecl', groups.Red, groups.Red, groups.Red)
Group.new('javaVarArg', groups.Fg, groups.Fg, groups.Fg)
Group.new('javaAnnotation', groups.Purple, groups.Purple, groups.Purple)
Group.new('javaUserLabel', groups.Purple, groups.Purple, groups.Purple)
Group.new('javaTypedef', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('javaParen', groups.Fg, groups.Fg, groups.Fg)
Group.new('javaParen1', groups.Fg, groups.Fg, groups.Fg)
Group.new('javaParen2', groups.Fg, groups.Fg, groups.Fg)
Group.new('javaParen3', groups.Fg, groups.Fg, groups.Fg)
Group.new('javaParen4', groups.Fg, groups.Fg, groups.Fg)
Group.new('javaParen5', groups.Fg, groups.Fg, groups.Fg)




Group.new('ktSimpleInterpolation', groups.Purple, groups.Purple, groups.Purple)
Group.new('ktComplexInterpolation', groups.Purple, groups.Purple, groups.Purple)
Group.new('ktComplexInterpolationBrace', groups.Purple, groups.Purple, groups.Purple)
Group.new('ktStructure', groups.Red, groups.Red, groups.Red)
Group.new('ktKeyword', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)




Group.new('scalaNameDefinition', groups.Fg, groups.Fg, groups.Fg)
Group.new('scalaInterpolationBoundary', groups.Purple, groups.Purple, groups.Purple)
Group.new('scalaInterpolation', groups.Purple, groups.Purple, groups.Purple)
Group.new('scalaTypeOperator', groups.Red, groups.Red, groups.Red)
Group.new('scalaOperator', groups.Red, groups.Red, groups.Red)
Group.new('scalaKeywordModifier', groups.Red, groups.Red, groups.Red)




Group.new('goDirective', groups.Red, groups.Red, groups.Red)
Group.new('goConstants', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('goDeclType', groups.Red, groups.Red, groups.Red)


Group.new('goPackage', groups.Red, groups.Red, groups.Red)
Group.new('goImport', groups.Red, groups.Red, groups.Red)
Group.new('goBuiltins', groups.Green, groups.Green, groups.Green)
Group.new('goPredefinedIdentifiers', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('goVar', groups.Red, groups.Red, groups.Red)




Group.new('rustStructure', groups.Red, groups.Red, groups.Red)
Group.new('rustIdentifier', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('rustModPath', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('rustModPathSep', groups.Grey, groups.Grey, groups.Grey)
Group.new('rustSelf', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('rustSuper', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('rustDeriveTrait', groups.Purple, groups.Purple, groups.Purple)
Group.new('rustEnumVariant', groups.Purple, groups.Purple, groups.Purple)
Group.new('rustMacroVariable', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('rustAssert', groups.Green, groups.Green, groups.Green)
Group.new('rustPanic', groups.Green, groups.Green, groups.Green)
Group.new('rustPubScopeCrate', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('rustAttribute', groups.Purple, groups.Purple, groups.Purple)




Group.new('swiftInterpolatedWrapper', groups.Purple, groups.Purple, groups.Purple)
Group.new('swiftInterpolatedString', groups.Purple, groups.Purple, groups.Purple)
Group.new('swiftProperty', groups.Fg, groups.Fg, groups.Fg)
Group.new('swiftTypeDeclaration', groups.Red, groups.Red, groups.Red)
Group.new('swiftClosureArgument', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('swiftStructure', groups.Red, groups.Red, groups.Red)




Group.new('phpVarSelector', groups.Fg, groups.Fg, groups.Fg)
Group.new('phpIdentifier', groups.Fg, groups.Fg, groups.Fg)
Group.new('phpDefine', groups.Green, groups.Green, groups.Green)
Group.new('phpStructure', groups.Red, groups.Red, groups.Red)
Group.new('phpSpecialFunction', groups.Green, groups.Green, groups.Green)
Group.new('phpInterpSimpleCurly', groups.Purple, groups.Purple, groups.Purple)
Group.new('phpComparison', groups.Red, groups.Red, groups.Red)
Group.new('phpMethodsVar', groups.Fg, groups.Fg, groups.Fg)
Group.new('phpInterpVarname', groups.Fg, groups.Fg, groups.Fg)
Group.new('phpMemberSelector', groups.Red, groups.Red, groups.Red)
Group.new('phpLabel', groups.Red, groups.Red, groups.Red)


Group.new('phpParent', groups.Fg, groups.Fg, groups.Fg)
Group.new('phpNowDoc', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('phpFunction', groups.Green, groups.Green, groups.Green)
Group.new('phpMethod', groups.Green, groups.Green, groups.Green)
Group.new('phpClass', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('phpSuperglobals', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('phpNullValue', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)




Group.new('rubyKeywordAsMethod', groups.Green, groups.Green, groups.Green)
Group.new('rubyInterpolation', groups.Purple, groups.Purple, groups.Purple)
Group.new('rubyInterpolationDelimiter', groups.Purple, groups.Purple, groups.Purple)
Group.new('rubyStringDelimiter', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('rubyBlockParameterList', groups.Fg, groups.Fg, groups.Fg)
Group.new('rubyDefine', groups.Red, groups.Red, groups.Red)
Group.new('rubyModuleName', groups.Red, groups.Red, groups.Red)
Group.new('rubyAccess', groups.Red, groups.Red, groups.Red)
Group.new('rubyMacro', groups.Red, groups.Red, groups.Red)
Group.new('rubySymbol', groups.Fg, groups.Fg, groups.Fg)




Group.new('haskellBrackets', groups.Fg, groups.Fg, groups.Fg)
Group.new('haskellIdentifier', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('haskellDecl', groups.Red, groups.Red, groups.Red)
Group.new('haskellType', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('haskellDeclKeyword', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('haskellWhere', groups.PurpleItalic, groups.PurpleItalic, groups.PurpleItalic)
Group.new('haskellDeriveKeyword', groups.Red, groups.Red, groups.Red)
Group.new('haskellOperators', groups.Red, groups.Red, groups.Red)
Group.new('haskellForeignKeywords', groups.Red, groups.Red, groups.Red)




Group.new('perlStatementPackage', groups.Red, groups.Red, groups.Red)
Group.new('perlStatementInclude', groups.Red, groups.Red, groups.Red)
Group.new('perlStatementStorage', groups.Red, groups.Red, groups.Red)
Group.new('perlStatementList', groups.Red, groups.Red, groups.Red)
Group.new('perlMatchStartEnd', groups.Red, groups.Red, groups.Red)
Group.new('perlVarSimpleMemberName', groups.Green, groups.Green, groups.Green)
Group.new('perlVarSimpleMember', groups.Fg, groups.Fg, groups.Fg)
Group.new('perlMethod', groups.Green, groups.Green, groups.Green)
Group.new('podVerbatimLine', groups.Green, groups.Green, groups.Green)
Group.new('podCmdText', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('perlVarPlain', groups.Fg, groups.Fg, groups.Fg)
Group.new('perlVarPlain2', groups.Fg, groups.Fg, groups.Fg)




Group.new('ocamlArrow', groups.Red, groups.Red, groups.Red)
Group.new('ocamlEqual', groups.Red, groups.Red, groups.Red)
Group.new('ocamlOperator', groups.Red, groups.Red, groups.Red)
Group.new('ocamlKeyChar', groups.Red, groups.Red, groups.Red)
Group.new('ocamlModPath', groups.Green, groups.Green, groups.Green)
Group.new('ocamlFullMod', groups.Green, groups.Green, groups.Green)
Group.new('ocamlModule', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('ocamlConstructor', groups.Orange, groups.Orange, groups.Orange)
Group.new('ocamlModParam', groups.Fg, groups.Fg, groups.Fg)
Group.new('ocamlModParam1', groups.Fg, groups.Fg, groups.Fg)
Group.new('ocamlAnyVar', groups.Fg, groups.Fg, groups.Fg)
Group.new('ocamlPpxEncl', groups.Red, groups.Red, groups.Red)
Group.new('ocamlPpxIdentifier', groups.Fg, groups.Fg, groups.Fg)
Group.new('ocamlSigEncl', groups.Red, groups.Red, groups.Red)
Group.new('ocamlModParam1', groups.Fg, groups.Fg, groups.Fg)




Group.new('erlangAtom', groups.Fg, groups.Fg, groups.Fg)
Group.new('erlangVariable', groups.Fg, groups.Fg, groups.Fg)
Group.new('erlangLocalFuncRef', groups.Green, groups.Green, groups.Green)
Group.new('erlangLocalFuncCall', groups.Green, groups.Green, groups.Green)
Group.new('erlangGlobalFuncRef', groups.Green, groups.Green, groups.Green)
Group.new('erlangGlobalFuncCall', groups.Green, groups.Green, groups.Green)
Group.new('erlangAttribute', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('erlangPipe', groups.Red, groups.Red, groups.Red)




Group.new('elixirStringDelimiter', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('elixirKeyword', groups.Red, groups.Red, groups.Red)
Group.new('elixirInterpolation', groups.Purple, groups.Purple, groups.Purple)
Group.new('elixirInterpolationDelimiter', groups.Purple, groups.Purple, groups.Purple)
Group.new('elixirSelf', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('elixirPseudoVariable', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('elixirModuleDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirBlockDefinition', groups.Red, groups.Red, groups.Red)
Group.new('elixirDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirPrivateDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirGuard', groups.Red, groups.Red, groups.Red)
Group.new('elixirPrivateGuard', groups.Red, groups.Red, groups.Red)
Group.new('elixirProtocolDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirImplDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirRecordDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirPrivateRecordDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirMacroDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirPrivateMacroDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirDelegateDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirOverridableDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirExceptionDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirCallbackDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirStructDefine', groups.Red, groups.Red, groups.Red)
Group.new('elixirExUnitMacro', groups.Red, groups.Red, groups.Red)




Group.new('lispAtomMark', groups.Purple, groups.Purple, groups.Purple)
Group.new('lispKey', groups.Orange, groups.Orange, groups.Orange)
Group.new('lispFunc', groups.Green, groups.Green, groups.Green)




Group.new('clojureMacro', groups.Red, groups.Red, groups.Red)
Group.new('clojureFunc', groups.Green, groups.Green, groups.Green)
Group.new('clojureConstant', groups.OrangeItalic, groups.OrangeItalic, groups.OrangeItalic)
Group.new('clojureSpecial', groups.Red, groups.Red, groups.Red)
Group.new('clojureDefine', groups.Red, groups.Red, groups.Red)
Group.new('clojureKeyword', groups.Blue, groups.Blue, groups.Blue)
Group.new('clojureVariable', groups.Fg, groups.Fg, groups.Fg)
Group.new('clojureMeta', groups.Purple, groups.Purple, groups.Purple)
Group.new('clojureDeref', groups.Purple, groups.Purple, groups.Purple)




Group.new('matlabSemicolon', groups.Fg, groups.Fg, groups.Fg)
Group.new('matlabFunction', groups.RedItalic, groups.RedItalic, groups.RedItalic)
Group.new('matlabImplicit', groups.Green, groups.Green, groups.Green)
Group.new('matlabDelimiter', groups.Fg, groups.Fg, groups.Fg)
Group.new('matlabOperator', groups.Green, groups.Green, groups.Green)
Group.new('matlabArithmeticOperator', groups.Red, groups.Red, groups.Red)
Group.new('matlabArithmeticOperator', groups.Red, groups.Red, groups.Red)
Group.new('matlabRelationalOperator', groups.Red, groups.Red, groups.Red)
Group.new('matlabRelationalOperator', groups.Red, groups.Red, groups.Red)
Group.new('matlabLogicalOperator', groups.Red, groups.Red, groups.Red)




Group.new('shRange', groups.Fg, groups.Fg, groups.Fg)
Group.new('shOption', groups.Purple, groups.Purple, groups.Purple)
Group.new('shQuote', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('shVariable', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('shDerefSimple', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('shDerefVar', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('shDerefSpecial', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('shDerefOff', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('shVarAssign', groups.Red, groups.Red, groups.Red)
Group.new('shFunctionOne', groups.Green, groups.Green, groups.Green)
Group.new('shFunctionKey', groups.Red, groups.Red, groups.Red)




Group.new('zshOption', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('zshSubst', groups.Orange, groups.Orange, groups.Orange)
Group.new('zshFunction', groups.Green, groups.Green, groups.Green)




Group.new('ps1FunctionInvocation', groups.Green, groups.Green, groups.Green)
Group.new('ps1FunctionDeclaration', groups.Green, groups.Green, groups.Green)
Group.new('ps1InterpolationDelimiter', groups.Purple, groups.Purple, groups.Purple)
Group.new('ps1BuiltIn', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)



Group.new('vimLet', groups.Red, groups.Red, groups.Red)
Group.new('vimFunction', groups.Green, groups.Green, groups.Green)
Group.new('vimIsCommand', groups.Fg, groups.Fg, groups.Fg)
Group.new('vimUserFunc', groups.Green, groups.Green, groups.Green)
Group.new('vimFuncName', groups.Green, groups.Green, groups.Green)
Group.new('vimMap', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('vimNotation', groups.Purple, groups.Purple, groups.Purple)
Group.new('vimMapLhs', groups.Green, groups.Green, groups.Green)
Group.new('vimMapRhs', groups.Green, groups.Green, groups.Green)
Group.new('vimSetEqual', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('vimSetSep', groups.Fg, groups.Fg, groups.Fg)
Group.new('vimOption', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('vimUserAttrbKey', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('vimUserAttrb', groups.Green, groups.Green, groups.Green)
Group.new('vimAutoCmdSfxList', groups.Orange, groups.Orange, groups.Orange)
Group.new('vimSynType', groups.Orange, groups.Orange, groups.Orange)
Group.new('vimHiBang', groups.Orange, groups.Orange, groups.Orange)
Group.new('vimSet', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('vimSetSep', groups.Grey, groups.Grey, groups.Grey)


Group.new('makeIdent', groups.Purple, groups.Purple, groups.Purple)
Group.new('makeSpecTarget', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('makeTarget', groups.Orange, groups.Orange, groups.Orange)
Group.new('makeCommands', groups.Red, groups.Red, groups.Red)


Group.new('cmakeCommand', groups.Red, groups.Red, groups.Red)
Group.new('cmakeKWconfigure_package_config_file', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('cmakeKWwrite_basic_package_version_file', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('cmakeKWExternalProject', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_compile_definitions', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_compile_options', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_custom_command', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_custom_target', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_definitions', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_dependencies', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_executable', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_library', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_link_options', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_subdirectory', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWadd_test', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWbuild_command', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWcmake_host_system_information', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWcmake_minimum_required', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWcmake_parse_arguments', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWcmake_policy', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWconfigure_file', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWcreate_test_sourcelist', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWctest_build', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWctest_configure', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWctest_coverage', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWctest_memcheck', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWctest_run_script', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWctest_start', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWctest_submit', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWctest_test', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWctest_update', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWctest_upload', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWdefine_property', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWdoxygen_add_docs', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWenable_language', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWenable_testing', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWexec_program', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWexecute_process', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWexport', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWexport_library_dependencies', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWfile', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWfind_file', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWfind_library', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWfind_package', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWfind_path', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWfind_program', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWfltk_wrap_ui', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWforeach', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWfunction', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWget_cmake_property', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWget_directory_property', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWget_filename_component', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWget_property', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWget_source_file_property', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWget_target_property', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWget_test_property', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWif', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWinclude', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWinclude_directories', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWinclude_external_msproject', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWinclude_guard', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWinstall', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWinstall_files', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWinstall_programs', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWinstall_targets', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWlink_directories', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWlist', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWload_cache', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWload_command', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWmacro', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWmark_as_advanced', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWmath', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWmessage', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWoption', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWproject', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWqt_wrap_cpp', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWqt_wrap_ui', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWremove', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWseparate_arguments', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWset', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWset_directory_properties', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWset_property', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWset_source_files_properties', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWset_target_properties', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWset_tests_properties', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWsource_group', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWstring', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWsubdirs', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtarget_compile_definitions', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtarget_compile_features', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtarget_compile_options', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtarget_include_directories', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtarget_link_directories', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtarget_link_libraries', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtarget_link_options', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtarget_precompile_headers', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtarget_sources', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtry_compile', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWtry_run', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWunset', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWuse_mangled_mesa', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWvariable_requires', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWvariable_watch', groups.Green, groups.Green, groups.Green)
Group.new('cmakeKWwrite_file', groups.Green, groups.Green, groups.Green)


Group.new('jsonKeyword', groups.Red, groups.Red, groups.Red)
Group.new('jsonString', groups.Green, groups.Green, groups.Green)
Group.new('jsonBoolean', groups.Blue, groups.Blue, groups.Blue)
Group.new('jsonNoise', groups.Grey, groups.Grey, groups.Grey)
Group.new('jsonQuote', groups.Grey, groups.Grey, groups.Grey)
Group.new('jsonBraces', groups.Fg, groups.Fg, groups.Fg)


Group.new('yamlKey', groups.Red, groups.Red, groups.Red)
Group.new('yamlConstant', groups.BlueItalic, groups.BlueItalic, groups.BlueItalic)
Group.new('yamlString', groups.Green, groups.Green, groups.Green)


Group.new('tomlTable', colors.purple, colors.none, styles.bold)
Group.new('tomlKey', groups.Red, groups.Red, groups.Red)
Group.new('tomlBoolean', groups.Blue, groups.Blue, groups.Blue)
Group.new('tomlString', groups.Green, groups.Green, groups.Green)
Group.new('tomlTableArray', groups.tomlTable, groups.tomlTable, groups.tomlTable)


Group.new('diffAdded', groups.Green, groups.Green, groups.Green)
Group.new('diffRemoved', groups.Red, groups.Red, groups.Red)
Group.new('diffChanged', groups.Blue, groups.Blue, groups.Blue)
Group.new('diffOldFile', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('diffNewFile', groups.Orange, groups.Orange, groups.Orange)
Group.new('diffFile', groups.Purple, groups.Purple, groups.Purple)
Group.new('diffLine', groups.Grey, groups.Grey, groups.Grey)
Group.new('diffIndexLine', groups.Purple, groups.Purple, groups.Purple)


Group.new('gitcommitSummary', groups.Red, groups.Red, groups.Red)
Group.new('gitcommitUntracked', groups.Grey, groups.Grey, groups.Grey)
Group.new('gitcommitDiscarded', groups.Grey, groups.Grey, groups.Grey)
Group.new('gitcommitSelected', groups.Grey, groups.Grey, groups.Grey)
Group.new('gitcommitUnmerged', groups.Grey, groups.Grey, groups.Grey)
Group.new('gitcommitOnBranch', groups.Grey, groups.Grey, groups.Grey)
Group.new('gitcommitArrow', groups.Grey, groups.Grey, groups.Grey)
Group.new('gitcommitFile', groups.Green, groups.Green, groups.Green)


Group.new('dosiniHeader', colors.red, colors.none, styles.bold)
Group.new('dosiniLabel', groups.Blue, groups.Blue, groups.Blue)
Group.new('dosiniValue', groups.Green, groups.Green, groups.Green)
Group.new('dosiniNumber', groups.Green, groups.Green, groups.Green)


Group.new('helpNote', colors.purple, colors.none, styles.bold)
Group.new('helpHeadline', colors.red, colors.none, styles.bold)
Group.new('helpHeader', colors.orange, colors.none, styles.bold)
Group.new('helpURL', colors.green, colors.none, styles.underline)
Group.new('helpHyperTextEntry', colors.blue, colors.none, styles.bold)
Group.new('helpHyperTextJump', groups.Blue, groups.Blue, groups.Blue)
Group.new('helpCommand', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('helpExample', groups.Green, groups.Green, groups.Green)
Group.new('helpSpecial', groups.Purple, groups.Purple, groups.Purple)
Group.new('helpSectionDelim', groups.Grey, groups.Grey, groups.Grey)




Group.new('CocHighlightText', colors.none, colors.none, styles.italic)
Group.new('CocHoverRange', colors.none, colors.none, styles.bold + styles.underline)
Group.new('CocHintHighlight', colors.none, colors.none, styles.undercurl)
Group.new('CocErrorFloat', colors.red, colors.bg2, nil)
Group.new('CocWarningFloat', colors.yellow, colors.bg2, nil)
Group.new('CocInfoFloat', colors.blue, colors.bg2, nil)
Group.new('CocHintFloat', colors.green, colors.bg2, nil)
Group.new('CocHintSign', colors.purple, colors.bg1, nil)
Group.new('CocCodeLens', groups.Grey, groups.Grey, groups.Grey)
Group.new('CocErrorSign', groups.ALEErrorSign, groups.ALEErrorSign, groups.ALEErrorSign)
Group.new('CocWarningSign', groups.ALEWarningSign, groups.ALEWarningSign, groups.ALEWarningSign)
Group.new('CocInfoSign', groups.ALEInfoSign, groups.ALEInfoSign, groups.ALEInfoSign)
Group.new('CocHintSign', groups.Label, groups.Label, groups.Label)
Group.new('CocErrorHighlight', groups.ALEError, groups.ALEError, groups.ALEError)
Group.new('CocWarningHighlight', groups.ALEWarning, groups.ALEWarning, groups.ALEWarning)
Group.new('CocInfoHighlight', groups.ALEInfo, groups.ALEInfo, groups.ALEInfo)
Group.new('CocWarningVirtualText', groups.ALEVirtualTextWarning, groups.ALEVirtualTextWarning, groups.ALEVirtualTextWarning)
Group.new('CocErrorVirtualText', groups.ALEVirtualTextError, groups.ALEVirtualTextError, groups.ALEVirtualTextError)
Group.new('CocInfoVirtualText', groups.ALEVirtualTextInfo, groups.ALEVirtualTextInfo, groups.ALEVirtualTextInfo)
Group.new('CocHintVirtualText', groups.ALEVirtualTextInfo, groups.ALEVirtualTextInfo, groups.ALEVirtualTextInfo)
Group.new('CocGitAddedSign', groups.GitGutterAdd, groups.GitGutterAdd, groups.GitGutterAdd)
Group.new('CocGitChangeRemovedSign', groups.GitGutterChangeDelete, groups.GitGutterChangeDelete, groups.GitGutterChangeDelete)
Group.new('CocGitChangedSign', groups.GitGutterChange, groups.GitGutterChange, groups.GitGutterChange)
Group.new('CocGitRemovedSign', groups.GitGutterDelete, groups.GitGutterDelete, groups.GitGutterDelete)
Group.new('CocGitTopRemovedSign', groups.GitGutterDelete, groups.GitGutterDelete, groups.GitGutterDelete)
Group.new('CocExplorerBufferRoot', groups.Red, groups.Red, groups.Red)
Group.new('CocExplorerBufferExpandIcon', groups.Blue, groups.Blue, groups.Blue)
Group.new('CocExplorerBufferBufnr', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('CocExplorerBufferModified', groups.Red, groups.Red, groups.Red)
Group.new('CocExplorerBufferBufname', groups.Grey, groups.Grey, groups.Grey)
Group.new('CocExplorerBufferFullpath', groups.Grey, groups.Grey, groups.Grey)
Group.new('CocExplorerFileRoot', groups.Red, groups.Red, groups.Red)
Group.new('CocExplorerFileExpandIcon', groups.Blue, groups.Blue, groups.Blue)
Group.new('CocExplorerFileFullpath', groups.Grey, groups.Grey, groups.Grey)
Group.new('CocExplorerFileDirectory', groups.Green, groups.Green, groups.Green)
Group.new('CocExplorerFileGitStage', groups.Blue, groups.Blue, groups.Blue)
Group.new('CocExplorerFileGitUnstage', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('CocExplorerFileSize', groups.Blue, groups.Blue, groups.Blue)
Group.new('CocExplorerTimeAccessed', groups.Purple, groups.Purple, groups.Purple)
Group.new('CocExplorerTimeCreated', groups.Purple, groups.Purple, groups.Purple)
Group.new('CocExplorerTimeModified', groups.Purple, groups.Purple, groups.Purple)
Group.new('CocExplorerFileRootName', groups.Orange, groups.Orange, groups.Orange)
Group.new('CocExplorerBufferNameVisible', groups.Green, groups.Green, groups.Green)


Group.new('StartifyBracket', groups.Grey, groups.Grey, groups.Grey)
Group.new('StartifyFile', groups.Green, groups.Green, groups.Green)
Group.new('StartifyNumber', groups.Orange, groups.Orange, groups.Orange)
Group.new('StartifyPath', groups.Grey, groups.Grey, groups.Grey)
Group.new('StartifySlash', groups.Grey, groups.Grey, groups.Grey)
Group.new('StartifySection', groups.Blue, groups.Blue, groups.Blue)
Group.new('StartifyHeader', groups.Red, groups.Red, groups.Red)
Group.new('StartifySpecial', groups.Grey, groups.Grey, groups.Grey)


Group.new('UndotreeSavedBig', colors.red, colors.none, styles.bold)
Group.new('UndotreeNode', groups.Blue, groups.Blue, groups.Blue)
Group.new('UndotreeNodeCurrent', groups.Purple, groups.Purple, groups.Purple)
Group.new('UndotreeSeq', groups.Green, groups.Green, groups.Green)
Group.new('UndotreeCurrent', groups.Blue, groups.Blue, groups.Blue)
Group.new('UndotreeNext', groups.Yellow, groups.Yellow, groups.Yellow)
Group.new('UndotreeTimeStamp', groups.Grey, groups.Grey, groups.Grey)
Group.new('UndotreeHead', groups.Purple, groups.Purple, groups.Purple)
Group.new('UndotreeBranch', groups.Blue, groups.Blue, groups.Blue)
Group.new('UndotreeSavedSmall', groups.Red, groups.Red, groups.Red)




-- let s:terminal = {
      -- \ 'black':    s:palette.black,
      -- \ 'red':      s:palette.red,
      -- \ 'yellow':   s:palette.yellow,
      -- \ 'green':    s:palette.green,
      -- \ 'cyan':     s:palette.orange,
      -- \ 'blue':     s:palette.blue,
      -- \ 'purple':   s:palette.purple,
      -- \ 'white':    s:palette.fg
      -- \ }
  --
