local c = require('cassiopeia.utils').colors
local s = require('cassiopeia.utils').styles
local Group = require('cassiopeia.utils').Group
local g = require('cassiopeia.utils').groups

-- Group.new('TSAnnotation'                                                   )
-- Group.new('TSAttribute'                                                    )
Group.new('TSBoolean'      , g.Boolean     , g.Boolean     , g.Boolean     )
Group.new('TSCharacter'    , g.Character   , g.Character   , g.Character   )
Group.new('TSComment'      , g.Comment     , g.Comment     , g.Comment     )
Group.new('TSConditional'  , g.Conditional , g.Conditional , g.Conditional )
Group.new('TSConstBuiltin' , g.Constant    , g.Constant    , g.Constant    )
Group.new('TSConstMacro'   , g.Constant    , g.Constant    , g.Constant    )
Group.new('TSConstant'     , g.Constant    , g.Constant    , g.Constant    )
-- Group.new('TSConstructor'                                                  )
-- Group.new('TSEmphasis'                                                     )
Group.new('TSError'        , g.Error       , g.Error       , g.Error       )
Group.new('TSException'    , g.Exception   , g.Exception   , g.Exception   )
-- Group.new('TSField'                                                        )
Group.new('TSFloat'        , g.Float       , g.Float       , g.Float       )
-- Group.new('TSFuncBuiltin'                                                  )
-- Group.new('TSFuncMacro'                                                    )
Group.new('TSFunction'     , g.Function    , g.Function    , g.Function    )
Group.new('TSInclude'      , g.Include     , g.Include     , g.Include     )
Group.new('TSKeyword'      , g.Keyword     , g.Keyword     , g.Keyword     )
-- Group.new('TSKeywordFunction'                                              )
-- Group.new('TSKeywordOperator'                                              )
-- Group.new('TSKeywordReturn'                                                )
Group.new('TSLabel'        , g.Label       , g.Label       , g.Label       )
-- Group.new('TSLiteral'                                                      )
-- Group.new('TSMethod'                                                       )
-- Group.new('TSNamespace'                                                    )
Group.new('TSNumber'       , g.Number      , g.Number      , g.Number      )
Group.new('TSOperator'     , g.Operator    , g.Operator    , g.Operator    )
-- Group.new('TSParameter'                                                    )
-- Group.new('TSParameterReference'                                           )
-- Group.new('TSProperty'                                                     )
-- Group.new('TSPunctBracket'                                                 )
-- Group.new('TSPunctDelimiter'                                               )
-- Group.new('TSPunctSpecial'                                                 )
-- Group.new('TSQueryLinterError'                                             )
Group.new('TSRepeat'       , g.Repeat      , g.Repeat      , g.Repeat      )
Group.new('TSString'       , g.String      , g.String      , g.String      )
-- Group.new('TSStringEscape'                                                 )
-- Group.new('TSStringRegex'                                                  )
-- Group.new('TSStrong'                                                       )
Group.new('TSStructure'    , g.Structure   , g.Structure   , g.Structure   )
-- Group.new('TSSymbol'                                                       )
Group.new('TSTag'          , g.Tag         , g.Tag         , g.Tag         )
-- Group.new('TSTagDelimiter'                                                 )
-- Group.new('TSText'                                                         )
Group.new('TSTitle'        , g.Title       , g.Title       , g.Title       )
-- Group.new('TSType'                                                         )
-- Group.new('TSTypeBuiltin'                                                  )
-- Group.new('TSURI'                                                          )
Group.new('TSUnderline'    , g.Underlined  , g.Underlined  , g.Underlined  )
-- Group.new('TSVariable'                                                     )
-- Group.new('TSVariableBuiltin'                                              )
